In [1]:
import pandas as pd
import numpy as np

pitchers = pd.read_csv('/Users/chrisgalgano/desktop/FantasyBBValues/2023_Standard_Pitching.csv')
starters = pd.read_csv('/Users/chrisgalgano/desktop/FantasyBBValues/2023_Starters_Pitching.csv')
relievers = pd.read_csv('/Users/chrisgalgano/desktop/FantasyBBValues/2023_Relievers_Pitching.csv')

pitchers = pitchers.drop_duplicates(subset="Name-additional")
starters = starters.drop_duplicates(subset="Name-additional")
relievers = relievers.drop_duplicates(subset="Name-additional")


pitchers = pd.merge(pitchers,starters[['QS', 'Name-additional']],how = 'left', on = 'Name-additional')
pitchers = pd.merge(pitchers, relievers[['Hold', 'Name-additional']],how = 'left',on = 'Name-additional')

pp = []
for item in pitchers['GS']:
    temp = ''
    if item > 3:
        temp = 'SP'
    else:
        temp = 'RP'
    pp.append(temp)

pitchers['Pos'] = pp

pitchers = pitchers.fillna(0)

start = pitchers.loc[pitchers['Pos'] == 'SP']
start = start.drop((start[start['IP'] < 40] ).index)

rel = pitchers.loc[pitchers['Pos'] == 'RP']
rel = rel.drop((rel[rel['IP'] < 30] ).index)
rel = rel.drop((rel[rel['ERA'] > 5 ] ).index)

pitchers = pd.concat([start, rel])
pitchers = pitchers.drop_duplicates()
pitchers = pitchers.drop((pitchers[pitchers['Lg'] == 'MLB' ] ).index)

pitchers.to_csv('pitchers.csv', index= False)
pitchers

,Rk,Name,Age,Tm,Lg,W,L,W-L%,ERA,G,...,WHIP,H9,HR9,BB9,SO9,SO/W,Name-additional,QS,Hold,Pos
1,2,Andrew Abbott*,24,CIN,NL,5,2,0.714,2.10,9,...,0.916,5.3,1.3,2.9,9.2,3.17,abbotan01,7.0,0.0,SP
14,15,Sandy Alcantara,27,MIA,NL,3,9,0.250,4.70,20,...,1.282,9.0,1.0,2.6,7.6,2.94,alcansa01,8.0,0.0,SP
18,19,Logan Allen*,24,CLE,AL,4,2,0.667,3.21,13,...,1.366,9.0,0.8,3.3,9.5,2.84,allenlo02,4.0,0.0,SP
25,28,Tyler Anderson*,33,LAA,AL,4,2,0.667,5.17,17,...,1.552,9.9,1.0,4.0,7.6,1.87,anderty01,5.0,0.0,SP
28,31,Graham Ashcraft,25,CIN,NL,5,7,0.417,5.77,18,...,1.537,10.1,1.3,3.7,6.3,1.69,ashcrgr01,9.0,0.0,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,785,Bryse Wilson,25,MIL,NL,3,0,1.000,2.51,32,...,0.986,6.6,0.6,2.3,7.7,3.33,wilsobr02,0.0,3.0,RP
741,786,Steven Wilson,28,SDP,NL,1,0,1.000,2.70,38,...,1.025,5.2,0.9,4.1,9.5,2.33,wilsost02,0.0,18.0,RP
742,787,Josh Winckowski,25,BOS,AL,3,1,0.750,3.02,33,...,1.360,9.6,1.3,2.7,7.4,2.75,winckjo01,0.0,8.0,RP
758,803,Kirby Yates,36,ATL,NL,4,0,1.000,3.38,37,...,1.232,6.0,1.4,5.1,12.5,2.48,yateski01,0.0,5.0,RP
759,804,Alex Young*,29,CIN,NL,4,0,1.000,2.35,44,...,1.304,8.5,1.2,3.3,8.9,2.71,youngal01,0.0,10.0,RP

In [2]:
stats = pitchers[['Name', 'Pos', 'IP', 'SO', 'QS', 'W', 'SV', 'Hold', 'ERA', 'WHIP', 'ER', 'H', 'BB']]

lg_ERAavg = (9 *np.sum(stats['ER'])/np.sum(stats['IP']))
lg_WHIPavg = (np.sum(stats['H']) + np.sum(stats['BB']))/ np.sum(stats['IP'])
stats
lg_WHIPavg

1.2616585893921246

In [3]:

stats['Z_SO'] = round((stats['SO']-np.mean(stats['SO']))/np.std(stats['SO']),3)
stats['Z_QS'] = round((stats['QS']-np.mean(stats['QS']))/np.std(stats['QS']),3)
stats['Z_W'] = round((stats['W']-np.mean(stats['W']))/np.std(stats['W']),3)
stats['Z_SV'] = round((stats['SV']-np.mean(stats['SV']))/np.std(stats['SV']),3)
stats['Z_HOLD'] = round((stats['Hold']-np.mean(stats['Hold']))/np.std(stats['Hold']),3)
stats['EraOA'] = round(stats['ERA'] - (9*stats['IP']*lg_ERAavg),1)
stats['Z_ERA'] = round(((stats['EraOA']-np.mean(stats['EraOA']))/(np.std(stats['EraOA']))/4),3)
stats['WhipOA'] = round((stats['H']+stats['BB']) - (stats['IP'] * lg_WHIPavg),1)
stats['Z_WHIP'] = round(((stats['WhipOA']-np.mean(stats['WhipOA']))/(np.std(stats['WhipOA']))/4),3)
       
stats

'''
stats['Z_SO'] = round((stats['SO']-np.mean(stats['SO']))/np.std(stats['SO']),3)
stats['Z_QS'] = round((stats['QS']-np.mean(stats['QS']))/np.std(stats['QS']),3)
stats['Z_W'] = round((stats['W']-np.mean(stats['W']))/np.std(stats['W']),3)
stats['Z_SV'] = round((stats['SV']-np.mean(stats['SV']))/np.std(stats['SV']),3)
stats['Z_HOLD'] = round((stats['Hold']-np.mean(stats['Hold']))/np.std(stats['Hold']),3)
stats['Z_ERA'] = round(((stats['ERA']-np.mean(stats['ERA']))/(np.std(stats['ERA']))),3)
stats['Z_WHIP'] = round(((stats['WHIP']-np.mean(stats['WHIP']))/(np.std(stats['WHIP']))),3)
       
stats
'''

/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/3292208183.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['Z_SO'] = round((stats['SO']-np.mean(stats['SO']))/np.std(stats['SO']),3)
/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/3292208183.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['Z_QS'] = round((stats['QS']-np.mean(stats['QS']))/np.std(stats['QS']),3)
/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/3292208183.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['Z_W'] = round((stats['W']-np.mean(stats['W']))/np.std(stats['W']),3)
/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/3292208183.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['Z_SV'] = round((stats['SV']-np.mean(stats['SV']))/np.std(stats['SV']),3)
/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/3292208183.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['Z_HOLD'] = round((stats['Hold']-np.mean(stats['Hold']))/np.std(stats['Hold']),3)
/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/3292208183.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['EraOA'] = round(stats['ERA'] - (9*stats['IP']*lg_ERAavg),1)
/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/3292208183.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['Z_ERA'] = round(((stats['EraOA']-np.mean(stats['EraOA']))/(np.std(stats['EraOA']))/4),3)
/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/3292208183.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['WhipOA'] = round((stats['H']+stats['BB']) - (stats['IP'] * lg_WHIPavg),1)
/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/3292208183.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats['Z_WHIP'] = round(((stats['WhipOA']-np.mean(stats['WhipOA']))/(np.std(stats['WhipOA']))/4),3)

"\nstats['Z_SO'] = round((stats['SO']-np.mean(stats['SO']))/np.std(stats['SO']),3)\nstats['Z_QS'] = round((stats['QS']-np.mean(stats['QS']))/np.std(stats['QS']),3)\nstats['Z_W'] = round((stats['W']-np.mean(stats['W']))/np.std(stats['W']),3)\nstats['Z_SV'] = round((stats['SV']-np.mean(stats['SV']))/np.std(stats['SV']),3)\nstats['Z_HOLD'] = round((stats['Hold']-np.mean(stats['Hold']))/np.std(stats['Hold']),3)\nstats['Z_ERA'] = round(((stats['ERA']-np.mean(stats['ERA']))/(np.std(stats['ERA']))),3)\nstats['Z_WHIP'] = round(((stats['WHIP']-np.mean(stats['WHIP']))/(np.std(stats['WHIP']))),3)\n       \nstats\n"

In [4]:
zdata = stats[['Name','Pos','IP','SO','QS','W','SV','Hold','ERA', 'WHIP', 'Z_SO',
               'Z_QS','Z_W','Z_SV','Z_HOLD','Z_ERA', 'Z_WHIP']]

pos_z = zdata.groupby('Pos',as_index=False)['Z_SO','Z_QS','Z_W','Z_SV','Z_HOLD','Z_ERA','Z_WHIP'].mean()
pos_z.columns=['Pos','AVGZ_SO','AVGZ_QS','AVGZ_W','AVGZ_SV','AVGZ_HOLD','AVGZ_ERA','AVGZ_WHIP']
replace_z = zdata.groupby('Pos',as_index=False)['Z_SO','Z_QS','Z_W','Z_SV','Z_HOLD','Z_ERA','Z_WHIP'].min()
replace_z.columns=['Pos','RepZ_SO','RepZ_QS','RepZ_W','RepZ_SV','RepZ_HOLD','RepZ_ERA','RepZ_WHIP']

z_changes = pd.merge(pos_z,replace_z,on='Pos')
z_changes=z_changes.round(decimals=3)

zdata = pd.merge(zdata,z_changes,how='left',on='Pos')
zdata

/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/1753372857.py:4: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  pos_z = zdata.groupby('Pos',as_index=False)['Z_SO','Z_QS','Z_W','Z_SV','Z_HOLD','Z_ERA','Z_WHIP'].mean()
/var/folders/xb/k5jn_45j51v9dkktpk3b41ch0000gn/T/ipykernel_7265/1753372857.py:6: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  replace_z = zdata.groupby('Pos',as_index=False)['Z_SO','Z_QS','Z_W','Z_SV','Z_HOLD','Z_ERA','Z_WHIP'].min()

,Name,Pos,IP,SO,QS,W,SV,Hold,ERA,WHIP,...,AVGZ_HOLD,AVGZ_ERA,AVGZ_WHIP,RepZ_SO,RepZ_QS,RepZ_W,RepZ_SV,RepZ_HOLD,RepZ_ERA,RepZ_WHIP
0,Andrew Abbott*,SP,55.2,57,7.0,5,0,0.0,2.10,0.916,...,-0.618,-0.167,0.041,-1.231,-0.767,-1.529,-0.388,-0.665,-0.604,-0.580
1,Sandy Alcantara,SP,126.1,106,8.0,3,0,0.0,4.70,1.282,...,-0.618,-0.167,0.041,-1.231,-0.767,-1.529,-0.388,-0.665,-0.604,-0.580
2,Logan Allen*,SP,67.1,71,4.0,4,0,0.0,3.21,1.366,...,-0.618,-0.167,0.041,-1.231,-0.767,-1.529,-0.388,-0.665,-0.604,-0.580
3,Tyler Anderson*,SP,87.0,73,5.0,4,0,0.0,5.17,1.552,...,-0.618,-0.167,0.041,-1.231,-0.767,-1.529,-0.388,-0.665,-0.604,-0.580
4,Graham Ashcraft,SP,93.2,66,9.0,5,0,0.0,5.77,1.537,...,-0.618,-0.167,0.041,-1.231,-0.767,-1.529,-0.388,-0.665,-0.604,-0.580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,Bryse Wilson,RP,46.2,40,0.0,3,3,3.0,2.51,0.986,...,0.753,0.203,-0.050,-1.461,-0.767,-1.529,-0.388,-0.665,0.055,-0.368
311,Steven Wilson,RP,40.0,42,0.0,1,0,18.0,2.70,1.025,...,0.753,0.203,-0.050,-1.461,-0.767,-1.529,-0.388,-0.665,0.055,-0.368
312,Josh Winckowski,RP,53.2,44,0.0,3,2,8.0,3.02,1.360,...,0.753,0.203,-0.050,-1.461,-0.767,-1.529,-0.388,-0.665,0.055,-0.368
313,Kirby Yates,RP,37.1,52,0.0,4,2,5.0,3.38,1.232,...,0.753,0.203,-0.050,-1.461,-0.767,-1.529,-0.388,-0.665,0.055,-0.368
314,Alex Young*,RP,38.1,38,0.0,4,1,10.0,2.35,1.304,...,0.753,0.203,-0.050,-1.461,-0.767,-1.529,-0.388,-0.665,0.055,-0.368

In [5]:
zdata['Z_SO'] = zdata['Z_SO'] - zdata['RepZ_SO']
zdata['Z_QS'] = zdata['Z_QS'] - zdata['RepZ_QS']
zdata['Z_W'] = zdata['Z_W'] - zdata['RepZ_W']
zdata['Z_SV'] = zdata['Z_SV'] - zdata['RepZ_SV']
zdata['Z_HOLD'] = zdata['Z_HOLD'] - zdata['RepZ_HOLD']
zdata['Z_ERA'] = zdata['Z_ERA'] - zdata['RepZ_ERA']
zdata['Z_WHIP'] = zdata['Z_WHIP'] - zdata['RepZ_WHIP']
#zdata['ZScore'] = zdata['Z_R'] + zdata['Z_HR'] + zdata['Z_RBI'] + zdata['Z_SB'] + zdata['Z_AVG']
zdata['Score'] = (zdata['Z_SO'] + zdata['Z_QS'] + zdata['Z_W'] + zdata['Z_SV'] + 
                  zdata['Z_HOLD'] - zdata['Z_ERA'] - zdata['Z_WHIP'])/7
zdata = zdata.sort_values(by='Score',ascending=False)

totaldollars = (260*12*.4)
print('{}$ to spend'.format(totaldollars))

perplayer = round(totaldollars/len(zdata),1)
print('Average ${}/player'.format(perplayer))

zdata['ZAR'] = zdata['Score']/np.mean(zdata['Score'])
zdata['$'] = round(zdata['ZAR']*perplayer,2)

printdf = zdata[['Name','Pos','IP','SO','QS','W','SV','Hold','ERA','WHIP','Score','$']] 




printdf.to_csv('PitcherPlayerValues.csv', index= False)

1248.0$ to spend
Average $4.0/player